In [4]:
import numpy as np

def initialize_parameters(layer_dims):
    np.random.seed(42)  # For reproducibility
    parameters = {}
    L = len(layer_dims)
    
    # Loop through layers to initialize weights and biases
    for l in range(1, L):
        parameters[f"W{l}"] = np.random.randn(layer_dims[l], layer_dims[l - 1]) * 0.01
        parameters[f"b{l}"] = np.zeros((layer_dims[l], 1))
        
    return parameters


**Test the function initialize_parameters**


In [6]:
layer_dims = [784, 20, 7, 5, 10]
parameters = initialize_parameters(layer_dims)
print(parameters["W1"].shape)  # Should print (20, 784)
print(parameters["b1"].shape)  # Should print (20, 1)
print(parameters["W4"].shape)  # Should print (10, 5)
print(parameters["b4"].shape)  # Should print (10, 1)


(20, 784)
(20, 1)
(10, 5)
(10, 1)


In [7]:
def linear_forward(A, W, b):
    """
    Compute the linear part of a layer's forward propagation.
    
    Arguments:
    A -- activations from previous layer
    W -- weights matrix of current layer
    b -- bias vector of current layer
    
    Returns:
    Z -- linear component (W.A + b)
    linear_cache -- tuple (A, W, b) for backpropagation
    """
    Z = np.dot(W, A) + b
    linear_cache = (A, W, b)
    return Z, linear_cache


**Test the function linear_forward**


In [8]:
np.random.seed(42)
A_prev = np.random.randn(3, 2)
W = np.random.randn(4, 3)
b = np.random.randn(4, 1)

Z, cache = linear_forward(A_prev, W, b)
print("Z shape:", Z.shape)  # Should be (4, 2)
print("Z:", Z)


Z shape: (4, 2)
Z: [[ 0.48338097  0.15237448]
 [-1.33390458 -2.08407482]
 [ 0.7505205  -1.0779219 ]
 [-1.23465366 -1.76418096]]


**Softmax**

In [9]:
def softmax(Z):
    """
    Implements the softmax activation function.

    Arguments:
    Z -- numpy array of shape (number of classes, number of examples)

    Returns:
    A -- output of softmax(Z), same shape as Z
    activation_cache -- returns Z for use in backpropagation
    """
    Z_shifted = Z - np.max(Z, axis=0, keepdims=True)  # for numerical stability
    exp_Z = np.exp(Z_shifted)
    A = exp_Z / np.sum(exp_Z, axis=0, keepdims=True)
    
    activation_cache = Z
    return A, activation_cache


In [10]:
def relu(Z):
    """
    Implements the ReLU activation function.

    Arguments:
    Z -- numpy array of any shape

    Returns:
    A -- output of relu(Z), same shape as Z
    activation_cache -- returns Z for use in backpropagation
    """
    A = np.maximum(0, Z)
    activation_cache = Z
    return A, activation_cache


In [11]:
Z = np.array([[1, -1, 0],
              [2, -2, 3]])

A_relu, cache_relu = relu(Z)
A_softmax, cache_softmax = softmax(Z)

print("ReLU result:\n", A_relu)
print("Softmax result:\n", A_softmax)


ReLU result:
 [[1 0 0]
 [2 0 3]]
Softmax result:
 [[0.26894142 0.73105858 0.04742587]
 [0.73105858 0.26894142 0.95257413]]
